/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteka00;

/**
 *
 * @author Mharcin
 */
public class PracownikView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public PracownikView() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpMain = new javax.swing.JTabbedPane();
        pKsiegozbiorPV = new javax.swing.JPanel();
        lbWyszukajEgzemplarz_Ks = new javax.swing.JLabel();
        lbEAN_Ks = new javax.swing.JLabel();
        lbTytul_Ks = new javax.swing.JLabel();
        lbAutor_Ks = new javax.swing.JLabel();
        lbISBN_Ks = new javax.swing.JLabel();
        lbTyp_Ks = new javax.swing.JLabel();
        lbJezyk_Ks = new javax.swing.JLabel();
        lbTag_Ks = new javax.swing.JLabel();
        tfAutor_Ks = new javax.swing.JTextField();
        tfTytul_Ks = new javax.swing.JTextField();
        tfTag_Ks = new javax.swing.JTextField();
        tfISBN_Ks = new javax.swing.JTextField();
        tfEAN_Ks = new javax.swing.JTextField();
        cbTyp_Ks = new javax.swing.JComboBox<>();
        cbJezyk_Ks = new javax.swing.JComboBox<>();
        btSzukaj_Ks = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tListaKsiazek_Ks = new javax.swing.JTable();
        btSzczegolyEdytuj_Ks = new javax.swing.JButton();
        btDodaj_Ks = new javax.swing.JButton();
        pRezerwacjePV = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tListaRezerwacji_Rez = new javax.swing.JTable();
        btAnulujRezerwacje_Rez = new javax.swing.JButton();
        btPotwierdzWydanie_Rez = new javax.swing.JButton();
        lbListaRezerwacji_Rez = new javax.swing.JLabel();
        pWypozyczeniaPV = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tListaWypozyczonych_Wyp = new javax.swing.JTable();
        btPotwierdzZwrot_Wyp = new javax.swing.JButton();
        lbListaWypKs_Wyp = new javax.swing.JLabel();
        btUsun_Wyp = new javax.swing.JButton();
        pCzytelnicyPV = new javax.swing.JPanel();
        lbWyszukajCzyt_Czyt = new javax.swing.JLabel();
        lbImie_Czyt = new javax.swing.JLabel();
        lbNazwisko_Czyt = new javax.swing.JLabel();
        lbMiejscowosc_Czyt = new javax.swing.JLabel();
        tfNazwisko_Czyt = new javax.swing.JTextField();
        tfImie_Czyt = new javax.swing.JTextField();
        tfMiejscowosc_Czyt = new javax.swing.JTextField();
        btDodaj_Czyt = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tListaCzytelnikow_Czyt = new javax.swing.JTable();
        lbNrDomu_Czyt = new javax.swing.JLabel();
        tfUlica_Czyt = new javax.swing.JTextField();
        tfKodPocztowy_Czyt = new javax.swing.JTextField();
        tfNrDomu_Czyt = new javax.swing.JTextField();
        lbKodPocztowy_Czyt = new javax.swing.JLabel();
        lbUlica_Czyt = new javax.swing.JLabel();
        tfLogin_Czyt = new javax.swing.JTextField();
        lbLogin_Czyt = new javax.swing.JLabel();
        btSzczegolyEdytuj_Czyt = new javax.swing.JButton();
        btSzukaj_Czyt = new javax.swing.JButton();
        pProfilPV = new javax.swing.JPanel();
        tfNrDomu_Pro = new javax.swing.JTextField();
        lbKodPocztowy_Pro = new javax.swing.JLabel();
        lbImie_Pro = new javax.swing.JLabel();
        lbUlica_Pro = new javax.swing.JLabel();
        lbNazwisko_Pro = new javax.swing.JLabel();
        tfEMail_Pro = new javax.swing.JTextField();
        lbMiejscowosc_Pro = new javax.swing.JLabel();
        lbEMail_Pro = new javax.swing.JLabel();
        tfNazwisko_Pro = new javax.swing.JTextField();
        lbNrDomu_Pro = new javax.swing.JLabel();
        tfImie_Pro = new javax.swing.JTextField();
        tfUlica_Pro = new javax.swing.JTextField();
        tfKodPocztowy_Pro = new javax.swing.JTextField();
        tfMiejscowosc_Pro = new javax.swing.JTextField();
        btZapisz_Pro = new javax.swing.JButton();
        btAnuluj_Pro = new javax.swing.JButton();
        tfHaslo_Pro = new javax.swing.JTextField();
        lbHaslo_Pro = new javax.swing.JLabel();
        lbDaneProfilu_Pro = new javax.swing.JLabel();
        lbLogin_Pro = new javax.swing.JLabel();
        tfLogin_Pro = new javax.swing.JTextField();
        pAdministracjaPV = new javax.swing.JPanel();
        lbWyszukajPracownika_Adm = new javax.swing.JLabel();
        lbImie_Adm = new javax.swing.JLabel();
        lbNazwisko_Adm = new javax.swing.JLabel();
        lbMiejscowosc_Adm = new javax.swing.JLabel();
        tfNazwisko_Adm = new javax.swing.JTextField();
        tfImie_Adm = new javax.swing.JTextField();
        tfMiejscowosc_Adm = new javax.swing.JTextField();
        btDodaj_Adm = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tListaPracowników_Adm = new javax.swing.JTable();
        btUsun_Adm = new javax.swing.JButton();
        lbNrDomu_Adm = new javax.swing.JLabel();
        tfUlica_Adm = new javax.swing.JTextField();
        tfKodPocztowy_Adm = new javax.swing.JTextField();
        tfNrDomu_Adm = new javax.swing.JTextField();
        lbKodPocztowy_Adm = new javax.swing.JLabel();
        lbUlica_Adm = new javax.swing.JLabel();
        tfLogin_Adm = new javax.swing.JTextField();
        lbLogin_Adm = new javax.swing.JLabel();
        btAnuluj_Adm = new javax.swing.JButton();
        btZapisz_Adm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbWyszukajEgzemplarz_Ks.setText("Wyszukaj egzemplarz:");

        lbEAN_Ks.setText("EAN");
        lbEAN_Ks.setPreferredSize(new java.awt.Dimension(40, 15));

        lbTytul_Ks.setText("Tytuł");
        lbTytul_Ks.setPreferredSize(new java.awt.Dimension(40, 15));

        lbAutor_Ks.setText("Autor");
        lbAutor_Ks.setPreferredSize(new java.awt.Dimension(40, 15));

        lbISBN_Ks.setText("ISBN");
        lbISBN_Ks.setPreferredSize(new java.awt.Dimension(40, 15));

        lbTyp_Ks.setText("Typ");
        lbTyp_Ks.setPreferredSize(new java.awt.Dimension(40, 15));

        lbJezyk_Ks.setText("Język");
        lbJezyk_Ks.setPreferredSize(new java.awt.Dimension(40, 15));

        lbTag_Ks.setText("Tag");
        lbTag_Ks.setPreferredSize(new java.awt.Dimension(40, 15));

        tfAutor_Ks.setText("...");
        tfAutor_Ks.setPreferredSize(new java.awt.Dimension(160, 19));

        tfTytul_Ks.setText("...");
        tfTytul_Ks.setPreferredSize(new java.awt.Dimension(160, 19));

        tfTag_Ks.setText("...");
        tfTag_Ks.setPreferredSize(new java.awt.Dimension(160, 19));

        tfISBN_Ks.setText("...");
        tfISBN_Ks.setPreferredSize(new java.awt.Dimension(160, 19));

        tfEAN_Ks.setText("...");
        tfEAN_Ks.setPreferredSize(new java.awt.Dimension(160, 19));

        cbTyp_Ks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Książka", "Czasopismo", "Film" }));
        cbTyp_Ks.setPreferredSize(new java.awt.Dimension(160, 24));

        cbJezyk_Ks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "polski", "arabski", "angielski", "niemiecki", " " }));
        cbJezyk_Ks.setPreferredSize(new java.awt.Dimension(160, 24));

        btSzukaj_Ks.setText("Szukaj");

        tListaKsiazek_Ks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1111", "Mały Książę", "Antoine’a de Saint-Exupéry", "książka", "baśń", "baśń", "Arabski", "123-456-789"},
                {"1111", "Faust", "J.W. Goethe", "ksiażka", "dramat", "dramat", "polski", "777-777-777"}
            },
            new String [] {
                "EAN", "Tytuł", "Autor", "Typ", "Gatunek", "Tagi", "Język", "ISBN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tListaKsiazek_Ks);
        if (tListaKsiazek_Ks.getColumnModel().getColumnCount() > 0) {
            tListaKsiazek_Ks.getColumnModel().getColumn(0).setResizable(false);
            tListaKsiazek_Ks.getColumnModel().getColumn(1).setResizable(false);
            tListaKsiazek_Ks.getColumnModel().getColumn(2).setResizable(false);
            tListaKsiazek_Ks.getColumnModel().getColumn(3).setResizable(false);
            tListaKsiazek_Ks.getColumnModel().getColumn(4).setResizable(false);
            tListaKsiazek_Ks.getColumnModel().getColumn(5).setResizable(false);
            tListaKsiazek_Ks.getColumnModel().getColumn(6).setResizable(false);
            tListaKsiazek_Ks.getColumnModel().getColumn(7).setResizable(false);
            tListaKsiazek_Ks.getColumnModel().getColumn(7).setHeaderValue("ISBN");
        }

        btSzczegolyEdytuj_Ks.setText("Szczegóły / Edytuj");
        btSzczegolyEdytuj_Ks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSzczegolyEdytuj_KsActionPerformed(evt);
            }
        });

        btDodaj_Ks.setText("Dodaj");

        javax.swing.GroupLayout pKsiegozbiorPVLayout = new javax.swing.GroupLayout(pKsiegozbiorPV);
        pKsiegozbiorPV.setLayout(pKsiegozbiorPVLayout);
        pKsiegozbiorPVLayout.setHorizontalGroup(
            pKsiegozbiorPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKsiegozbiorPVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pKsiegozbiorPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbWyszukajEgzemplarz_Ks)
                    .addGroup(pKsiegozbiorPVLayout.createSequentialGroup()
                        .addComponent(lbISBN_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfISBN_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pKsiegozbiorPVLayout.createSequentialGroup()
                        .addComponent(lbAutor_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAutor_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pKsiegozbiorPVLayout.createSequentialGroup()
                        .addComponent(lbTag_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTag_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pKsiegozbiorPVLayout.createSequentialGroup()
                        .addComponent(lbTytul_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTytul_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pKsiegozbiorPVLayout.createSequentialGroup()
                        .addComponent(lbJezyk_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJezyk_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pKsiegozbiorPVLayout.createSequentialGroup()
                        .addComponent(lbEAN_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEAN_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pKsiegozbiorPVLayout.createSequentialGroup()
                        .addComponent(lbTyp_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTyp_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btSzukaj_Ks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDodaj_Ks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pKsiegozbiorPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSzczegolyEdytuj_Ks)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pKsiegozbiorPVLayout.setVerticalGroup(
            pKsiegozbiorPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKsiegozbiorPVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbWyszukajEgzemplarz_Ks)
                .addGap(18, 18, 18)
                .addGroup(pKsiegozbiorPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pKsiegozbiorPVLayout.createSequentialGroup()
                        .addGroup(pKsiegozbiorPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTytul_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTytul_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pKsiegozbiorPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAutor_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAutor_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pKsiegozbiorPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbISBN_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfISBN_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pKsiegozbiorPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTag_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTag_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pKsiegozbiorPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEAN_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEAN_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pKsiegozbiorPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTyp_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTyp_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pKsiegozbiorPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbJezyk_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbJezyk_Ks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSzukaj_Ks)
                        .addGap(18, 18, 18)
                        .addComponent(btDodaj_Ks))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSzczegolyEdytuj_Ks)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        tpMain.addTab("Księgozbiór", pKsiegozbiorPV);

        tListaRezerwacji_Rez.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"00001", "777", "jeden1", "Adam", "Kowal", "20-04-2016", "-"},
                {"00002", "333", "kot77", "Jan", "Kowalski", "21-04-2016", "-"}
            },
            new String [] {
                "ID rezerwacji", "EAN", "Login", "Imię", "Nazwisko", "Data rezerwacji", "Koniec rezerwacji"
            }
        ));
        jScrollPane3.setViewportView(tListaRezerwacji_Rez);

        btAnulujRezerwacje_Rez.setText("Anuluj rezerwację");
        btAnulujRezerwacje_Rez.setPreferredSize(new java.awt.Dimension(70, 25));

        btPotwierdzWydanie_Rez.setText("Potwierdz wydanie");
        btPotwierdzWydanie_Rez.setPreferredSize(new java.awt.Dimension(70, 25));

        lbListaRezerwacji_Rez.setText("Lista rezerwacji: ");

        javax.swing.GroupLayout pRezerwacjePVLayout = new javax.swing.GroupLayout(pRezerwacjePV);
        pRezerwacjePV.setLayout(pRezerwacjePVLayout);
        pRezerwacjePVLayout.setHorizontalGroup(
            pRezerwacjePVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRezerwacjePVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRezerwacjePVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRezerwacjePVLayout.createSequentialGroup()
                        .addGroup(pRezerwacjePVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btPotwierdzWydanie_Rez, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(btAnulujRezerwacje_Rez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE))
                    .addGroup(pRezerwacjePVLayout.createSequentialGroup()
                        .addComponent(lbListaRezerwacji_Rez)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pRezerwacjePVLayout.setVerticalGroup(
            pRezerwacjePVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRezerwacjePVLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbListaRezerwacji_Rez)
                .addGap(18, 18, 18)
                .addGroup(pRezerwacjePVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRezerwacjePVLayout.createSequentialGroup()
                        .addComponent(btPotwierdzWydanie_Rez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAnulujRezerwacje_Rez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        tpMain.addTab("Rezerwacje", pRezerwacjePV);

        tListaWypozyczonych_Wyp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"00001", "777", "dwa2", "Jan", "Nowak", "Jacek", "Kowalski", "20-04-2016"}
            },
            new String [] {
                "ID wypożyczenia", "EAN", "Login czytelnika", "Imię czytelnika", "Nazwisko czytelnika", "Imię pracownika", "Nazwisko pracownika", "Data wypożyczenia"
            }
        ));
        jScrollPane4.setViewportView(tListaWypozyczonych_Wyp);

        btPotwierdzZwrot_Wyp.setText("Potwierdź zwrot");

        lbListaWypKs_Wyp.setText("Lista wypożyczonych książek:");

        btUsun_Wyp.setText("Usuń");

        javax.swing.GroupLayout pWypozyczeniaPVLayout = new javax.swing.GroupLayout(pWypozyczeniaPV);
        pWypozyczeniaPV.setLayout(pWypozyczeniaPVLayout);
        pWypozyczeniaPVLayout.setHorizontalGroup(
            pWypozyczeniaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWypozyczeniaPVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pWypozyczeniaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pWypozyczeniaPVLayout.createSequentialGroup()
                        .addGroup(pWypozyczeniaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btPotwierdzZwrot_Wyp)
                            .addComponent(btUsun_Wyp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
                    .addGroup(pWypozyczeniaPVLayout.createSequentialGroup()
                        .addComponent(lbListaWypKs_Wyp)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pWypozyczeniaPVLayout.setVerticalGroup(
            pWypozyczeniaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWypozyczeniaPVLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbListaWypKs_Wyp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pWypozyczeniaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pWypozyczeniaPVLayout.createSequentialGroup()
                        .addComponent(btPotwierdzZwrot_Wyp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btUsun_Wyp))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        tpMain.addTab("Wypożyczennia", pWypozyczeniaPV);

        lbWyszukajCzyt_Czyt.setText("Wyszukaj czytelnika:");

        lbImie_Czyt.setText("Imię");
        lbImie_Czyt.setPreferredSize(new java.awt.Dimension(70, 15));

        lbNazwisko_Czyt.setText("Nazwisko");
        lbNazwisko_Czyt.setPreferredSize(new java.awt.Dimension(70, 15));

        lbMiejscowosc_Czyt.setText("MIejscowość");
        lbMiejscowosc_Czyt.setPreferredSize(new java.awt.Dimension(70, 15));

        tfNazwisko_Czyt.setText("...");
        tfNazwisko_Czyt.setPreferredSize(new java.awt.Dimension(160, 19));

        tfImie_Czyt.setText("...");
        tfImie_Czyt.setPreferredSize(new java.awt.Dimension(160, 19));

        tfMiejscowosc_Czyt.setText("...");
        tfMiejscowosc_Czyt.setPreferredSize(new java.awt.Dimension(160, 19));

        btDodaj_Czyt.setText("Dodaj");

        tListaCzytelnikow_Czyt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Krystian", "Karczyński", "Tarnów", "33-100", "Mickiewicza", "100", "etrapez"},
                {"Ala", "Makota", "Kraków", "22-777", "Maczety", "77", "kot00"}
            },
            new String [] {
                "Imię", "Nazwisko", "Miejscowość", "Kod pocztowy", "Ulica", "Nr domu", "Login"
            }
        ));
        jScrollPane5.setViewportView(tListaCzytelnikow_Czyt);
        if (tListaCzytelnikow_Czyt.getColumnModel().getColumnCount() > 0) {
            tListaCzytelnikow_Czyt.getColumnModel().getColumn(0).setResizable(false);
            tListaCzytelnikow_Czyt.getColumnModel().getColumn(1).setResizable(false);
            tListaCzytelnikow_Czyt.getColumnModel().getColumn(2).setResizable(false);
            tListaCzytelnikow_Czyt.getColumnModel().getColumn(3).setResizable(false);
            tListaCzytelnikow_Czyt.getColumnModel().getColumn(4).setResizable(false);
            tListaCzytelnikow_Czyt.getColumnModel().getColumn(5).setResizable(false);
            tListaCzytelnikow_Czyt.getColumnModel().getColumn(6).setResizable(false);
        }

        lbNrDomu_Czyt.setText("Nr domu");
        lbNrDomu_Czyt.setPreferredSize(new java.awt.Dimension(70, 15));

        tfUlica_Czyt.setText("...");
        tfUlica_Czyt.setPreferredSize(new java.awt.Dimension(160, 19));

        tfKodPocztowy_Czyt.setText("...");
        tfKodPocztowy_Czyt.setPreferredSize(new java.awt.Dimension(160, 19));

        tfNrDomu_Czyt.setText("...");
        tfNrDomu_Czyt.setPreferredSize(new java.awt.Dimension(160, 19));

        lbKodPocztowy_Czyt.setText("Kod pocztowy");
        lbKodPocztowy_Czyt.setPreferredSize(new java.awt.Dimension(70, 15));

        lbUlica_Czyt.setText("Ulica");
        lbUlica_Czyt.setPreferredSize(new java.awt.Dimension(70, 15));

        tfLogin_Czyt.setText("...");
        tfLogin_Czyt.setPreferredSize(new java.awt.Dimension(160, 19));

        lbLogin_Czyt.setText("Login");
        lbLogin_Czyt.setPreferredSize(new java.awt.Dimension(70, 15));

        btSzczegolyEdytuj_Czyt.setText("Szczegóły / Edytuj");
        btSzczegolyEdytuj_Czyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSzczegolyEdytuj_CzytActionPerformed(evt);
            }
        });

        btSzukaj_Czyt.setText("Szukaj");

        javax.swing.GroupLayout pCzytelnicyPVLayout = new javax.swing.GroupLayout(pCzytelnicyPV);
        pCzytelnicyPV.setLayout(pCzytelnicyPVLayout);
        pCzytelnicyPVLayout.setHorizontalGroup(
            pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCzytelnicyPVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbWyszukajCzyt_Czyt)
                    .addGroup(pCzytelnicyPVLayout.createSequentialGroup()
                        .addGroup(pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btSzukaj_Czyt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCzytelnicyPVLayout.createSequentialGroup()
                                .addComponent(lbLogin_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfLogin_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCzytelnicyPVLayout.createSequentialGroup()
                                .addComponent(lbKodPocztowy_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfKodPocztowy_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCzytelnicyPVLayout.createSequentialGroup()
                                .addComponent(lbMiejscowosc_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfMiejscowosc_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCzytelnicyPVLayout.createSequentialGroup()
                                .addComponent(lbNazwisko_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNazwisko_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCzytelnicyPVLayout.createSequentialGroup()
                                .addComponent(lbImie_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfImie_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCzytelnicyPVLayout.createSequentialGroup()
                                .addGroup(pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNrDomu_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbUlica_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfUlica_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(tfNrDomu_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addComponent(btDodaj_Czyt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSzczegolyEdytuj_Czyt)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCzytelnicyPVLayout.setVerticalGroup(
            pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCzytelnicyPVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbWyszukajCzyt_Czyt)
                .addGap(18, 18, 18)
                .addGroup(pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCzytelnicyPVLayout.createSequentialGroup()
                        .addGroup(pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbImie_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfImie_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNazwisko_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNazwisko_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMiejscowosc_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMiejscowosc_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbKodPocztowy_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfKodPocztowy_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbUlica_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUlica_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNrDomu_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNrDomu_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pCzytelnicyPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLogin_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLogin_Czyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btSzukaj_Czyt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDodaj_Czyt))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSzczegolyEdytuj_Czyt)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        tpMain.addTab("Czytelnicy", pCzytelnicyPV);

        tfNrDomu_Pro.setText("...");
        tfNrDomu_Pro.setPreferredSize(new java.awt.Dimension(160, 19));

        lbKodPocztowy_Pro.setText("Kod pocztowy");
        lbKodPocztowy_Pro.setPreferredSize(new java.awt.Dimension(70, 15));

        lbImie_Pro.setText("Imię");
        lbImie_Pro.setPreferredSize(new java.awt.Dimension(70, 15));

        lbUlica_Pro.setText("Ulica");
        lbUlica_Pro.setPreferredSize(new java.awt.Dimension(70, 15));

        lbNazwisko_Pro.setText("Nazwisko");
        lbNazwisko_Pro.setPreferredSize(new java.awt.Dimension(70, 15));

        tfEMail_Pro.setText("...");
        tfEMail_Pro.setPreferredSize(new java.awt.Dimension(160, 19));

        lbMiejscowosc_Pro.setText("MIejscowość");
        lbMiejscowosc_Pro.setPreferredSize(new java.awt.Dimension(70, 15));

        lbEMail_Pro.setText("E-mail");
        lbEMail_Pro.setPreferredSize(new java.awt.Dimension(70, 15));

        tfNazwisko_Pro.setText("...");
        tfNazwisko_Pro.setPreferredSize(new java.awt.Dimension(160, 19));

        lbNrDomu_Pro.setText("Nr domu");
        lbNrDomu_Pro.setPreferredSize(new java.awt.Dimension(70, 15));

        tfImie_Pro.setText("...");
        tfImie_Pro.setPreferredSize(new java.awt.Dimension(160, 19));

        tfUlica_Pro.setText("...");
        tfUlica_Pro.setPreferredSize(new java.awt.Dimension(160, 19));

        tfKodPocztowy_Pro.setText("...");
        tfKodPocztowy_Pro.setPreferredSize(new java.awt.Dimension(160, 19));

        tfMiejscowosc_Pro.setText("...");
        tfMiejscowosc_Pro.setPreferredSize(new java.awt.Dimension(160, 19));

        btZapisz_Pro.setText("Zapisz");

        btAnuluj_Pro.setText("Anuluj");

        tfHaslo_Pro.setText("...");
        tfHaslo_Pro.setPreferredSize(new java.awt.Dimension(160, 19));

        lbHaslo_Pro.setText("Hasło");
        lbHaslo_Pro.setPreferredSize(new java.awt.Dimension(70, 15));

        lbDaneProfilu_Pro.setText("Dane profilu:");

        lbLogin_Pro.setText("Login");

        tfLogin_Pro.setText("...");
        tfLogin_Pro.setPreferredSize(new java.awt.Dimension(160, 19));

        javax.swing.GroupLayout pProfilPVLayout = new javax.swing.GroupLayout(pProfilPV);
        pProfilPV.setLayout(pProfilPVLayout);
        pProfilPVLayout.setHorizontalGroup(
            pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProfilPVLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pProfilPVLayout.createSequentialGroup()
                        .addComponent(lbNazwisko_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNazwisko_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pProfilPVLayout.createSequentialGroup()
                        .addComponent(lbMiejscowosc_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMiejscowosc_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pProfilPVLayout.createSequentialGroup()
                        .addComponent(lbImie_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfImie_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pProfilPVLayout.createSequentialGroup()
                        .addComponent(lbUlica_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUlica_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pProfilPVLayout.createSequentialGroup()
                        .addComponent(lbNrDomu_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNrDomu_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pProfilPVLayout.createSequentialGroup()
                        .addComponent(lbKodPocztowy_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfKodPocztowy_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pProfilPVLayout.createSequentialGroup()
                        .addComponent(lbEMail_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEMail_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbDaneProfilu_Pro)
                    .addGroup(pProfilPVLayout.createSequentialGroup()
                        .addComponent(btZapisz_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAnuluj_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pProfilPVLayout.createSequentialGroup()
                        .addGroup(pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHaslo_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLogin_Pro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLogin_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfHaslo_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(890, Short.MAX_VALUE))
        );
        pProfilPVLayout.setVerticalGroup(
            pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProfilPVLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbDaneProfilu_Pro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbImie_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfImie_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNazwisko_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNazwisko_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMiejscowosc_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMiejscowosc_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbKodPocztowy_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKodPocztowy_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUlica_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUlica_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNrDomu_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNrDomu_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEMail_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEMail_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogin_Pro)
                    .addComponent(tfLogin_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHaslo_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHaslo_Pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pProfilPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btZapisz_Pro)
                    .addComponent(btAnuluj_Pro))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        tpMain.addTab("Profil", pProfilPV);

        lbWyszukajPracownika_Adm.setText("Wyszukaj pracownika:");

        lbImie_Adm.setText("Imię");
        lbImie_Adm.setPreferredSize(new java.awt.Dimension(70, 15));

        lbNazwisko_Adm.setText("Nazwisko");
        lbNazwisko_Adm.setPreferredSize(new java.awt.Dimension(70, 15));

        lbMiejscowosc_Adm.setText("MIejscowość");
        lbMiejscowosc_Adm.setPreferredSize(new java.awt.Dimension(70, 15));

        tfNazwisko_Adm.setText("...");
        tfNazwisko_Adm.setPreferredSize(new java.awt.Dimension(160, 19));

        tfImie_Adm.setText("...");
        tfImie_Adm.setPreferredSize(new java.awt.Dimension(160, 19));

        tfMiejscowosc_Adm.setText("...");
        tfMiejscowosc_Adm.setPreferredSize(new java.awt.Dimension(160, 19));

        btDodaj_Adm.setText("Dodaj");

        tListaPracowników_Adm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Krystian", "Karczyński", "Tarnów", "33-100", "Mickiewicza", "100", "etrapez"},
                {"Ala", "Makota", "Kraków", "22-777", "Maczety", "77", "kot00"}
            },
            new String [] {
                "Imię", "Nazwisko", "Miejscowość", "Kod pocztowy", "Ulica", "Nr domu", "Login"
            }
        ));
        jScrollPane2.setViewportView(tListaPracowników_Adm);
        if (tListaPracowników_Adm.getColumnModel().getColumnCount() > 0) {
            tListaPracowników_Adm.getColumnModel().getColumn(0).setResizable(false);
            tListaPracowników_Adm.getColumnModel().getColumn(1).setResizable(false);
            tListaPracowników_Adm.getColumnModel().getColumn(2).setResizable(false);
            tListaPracowników_Adm.getColumnModel().getColumn(3).setResizable(false);
            tListaPracowników_Adm.getColumnModel().getColumn(4).setResizable(false);
            tListaPracowników_Adm.getColumnModel().getColumn(5).setResizable(false);
            tListaPracowników_Adm.getColumnModel().getColumn(6).setResizable(false);
        }

        btUsun_Adm.setText("Usuń");
        btUsun_Adm.setPreferredSize(new java.awt.Dimension(70, 25));
        btUsun_Adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsun_AdmActionPerformed(evt);
            }
        });

        lbNrDomu_Adm.setText("Nr domu");
        lbNrDomu_Adm.setPreferredSize(new java.awt.Dimension(70, 15));

        tfUlica_Adm.setText("...");
        tfUlica_Adm.setPreferredSize(new java.awt.Dimension(160, 19));

        tfKodPocztowy_Adm.setText("...");
        tfKodPocztowy_Adm.setPreferredSize(new java.awt.Dimension(160, 19));

        tfNrDomu_Adm.setText("...");
        tfNrDomu_Adm.setPreferredSize(new java.awt.Dimension(160, 19));

        lbKodPocztowy_Adm.setText("Kod pocztowy");
        lbKodPocztowy_Adm.setPreferredSize(new java.awt.Dimension(70, 15));

        lbUlica_Adm.setText("Ulica");
        lbUlica_Adm.setPreferredSize(new java.awt.Dimension(70, 15));

        tfLogin_Adm.setText("...");
        tfLogin_Adm.setPreferredSize(new java.awt.Dimension(160, 19));

        lbLogin_Adm.setText("Login");
        lbLogin_Adm.setPreferredSize(new java.awt.Dimension(70, 15));

        btAnuluj_Adm.setText("Anuluj");
        btAnuluj_Adm.setPreferredSize(new java.awt.Dimension(70, 25));
        btAnuluj_Adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnuluj_AdmActionPerformed(evt);
            }
        });

        btZapisz_Adm.setText("Zapisz");
        btZapisz_Adm.setPreferredSize(new java.awt.Dimension(70, 25));

        javax.swing.GroupLayout pAdministracjaPVLayout = new javax.swing.GroupLayout(pAdministracjaPV);
        pAdministracjaPV.setLayout(pAdministracjaPVLayout);
        pAdministracjaPVLayout.setHorizontalGroup(
            pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAdministracjaPVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbWyszukajPracownika_Adm)
                    .addGroup(pAdministracjaPVLayout.createSequentialGroup()
                        .addGroup(pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pAdministracjaPVLayout.createSequentialGroup()
                                .addComponent(lbNazwisko_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNazwisko_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pAdministracjaPVLayout.createSequentialGroup()
                                .addComponent(lbMiejscowosc_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfMiejscowosc_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pAdministracjaPVLayout.createSequentialGroup()
                                .addComponent(lbImie_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfImie_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pAdministracjaPVLayout.createSequentialGroup()
                                .addComponent(lbUlica_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfUlica_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pAdministracjaPVLayout.createSequentialGroup()
                                .addComponent(lbNrDomu_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNrDomu_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pAdministracjaPVLayout.createSequentialGroup()
                                .addComponent(lbKodPocztowy_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfKodPocztowy_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pAdministracjaPVLayout.createSequentialGroup()
                                .addComponent(lbLogin_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfLogin_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pAdministracjaPVLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btDodaj_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pAdministracjaPVLayout.createSequentialGroup()
                                .addComponent(btZapisz_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAnuluj_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btUsun_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pAdministracjaPVLayout.setVerticalGroup(
            pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAdministracjaPVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbWyszukajPracownika_Adm)
                .addGap(18, 18, 18)
                .addGroup(pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAdministracjaPVLayout.createSequentialGroup()
                        .addGroup(pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbImie_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfImie_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNazwisko_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNazwisko_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMiejscowosc_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMiejscowosc_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbKodPocztowy_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfKodPocztowy_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbUlica_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUlica_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNrDomu_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNrDomu_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLogin_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLogin_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btDodaj_Adm))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAdministracjaPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btZapisz_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAnuluj_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btUsun_Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        tpMain.addTab("Administracja", pAdministracjaPV);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(tpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAnuluj_AdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnuluj_AdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAnuluj_AdmActionPerformed

    private void btUsun_AdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsun_AdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btUsun_AdmActionPerformed

    private void btSzczegolyEdytuj_KsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSzczegolyEdytuj_KsActionPerformed
        // TODO add your handling code here:
        SzczegEgzemplarza szczegoly = new SzczegEgzemplarza();
        szczegoly.setVisible(true);
    }//GEN-LAST:event_btSzczegolyEdytuj_KsActionPerformed

    private void btSzczegolyEdytuj_CzytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSzczegolyEdytuj_CzytActionPerformed
        // TODO add your handling code here:
        SzczegCzytelnika szczegCzytelnika = new SzczegCzytelnika();
        szczegCzytelnika.setVisible(true);      
    }//GEN-LAST:event_btSzczegolyEdytuj_CzytActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracownikView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracownikView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracownikView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracownikView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracownikView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnulujRezerwacje_Rez;
    private javax.swing.JButton btAnuluj_Adm;
    private javax.swing.JButton btAnuluj_Pro;
    private javax.swing.JButton btDodaj_Adm;
    private javax.swing.JButton btDodaj_Czyt;
    private javax.swing.JButton btDodaj_Ks;
    private javax.swing.JButton btPotwierdzWydanie_Rez;
    private javax.swing.JButton btPotwierdzZwrot_Wyp;
    private javax.swing.JButton btSzczegolyEdytuj_Czyt;
    private javax.swing.JButton btSzczegolyEdytuj_Ks;
    private javax.swing.JButton btSzukaj_Czyt;
    private javax.swing.JButton btSzukaj_Ks;
    private javax.swing.JButton btUsun_Adm;
    private javax.swing.JButton btUsun_Wyp;
    private javax.swing.JButton btZapisz_Adm;
    private javax.swing.JButton btZapisz_Pro;
    private javax.swing.JComboBox<String> cbJezyk_Ks;
    private javax.swing.JComboBox<String> cbTyp_Ks;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbAutor_Ks;
    private javax.swing.JLabel lbDaneProfilu_Pro;
    private javax.swing.JLabel lbEAN_Ks;
    private javax.swing.JLabel lbEMail_Pro;
    private javax.swing.JLabel lbHaslo_Pro;
    private javax.swing.JLabel lbISBN_Ks;
    private javax.swing.JLabel lbImie_Adm;
    private javax.swing.JLabel lbImie_Czyt;
    private javax.swing.JLabel lbImie_Pro;
    private javax.swing.JLabel lbJezyk_Ks;
    private javax.swing.JLabel lbKodPocztowy_Adm;
    private javax.swing.JLabel lbKodPocztowy_Czyt;
    private javax.swing.JLabel lbKodPocztowy_Pro;
    private javax.swing.JLabel lbListaRezerwacji_Rez;
    private javax.swing.JLabel lbListaWypKs_Wyp;
    private javax.swing.JLabel lbLogin_Adm;
    private javax.swing.JLabel lbLogin_Czyt;
    private javax.swing.JLabel lbLogin_Pro;
    private javax.swing.JLabel lbMiejscowosc_Adm;
    private javax.swing.JLabel lbMiejscowosc_Czyt;
    private javax.swing.JLabel lbMiejscowosc_Pro;
    private javax.swing.JLabel lbNazwisko_Adm;
    private javax.swing.JLabel lbNazwisko_Czyt;
    private javax.swing.JLabel lbNazwisko_Pro;
    private javax.swing.JLabel lbNrDomu_Adm;
    private javax.swing.JLabel lbNrDomu_Czyt;
    private javax.swing.JLabel lbNrDomu_Pro;
    private javax.swing.JLabel lbTag_Ks;
    private javax.swing.JLabel lbTyp_Ks;
    private javax.swing.JLabel lbTytul_Ks;
    private javax.swing.JLabel lbUlica_Adm;
    private javax.swing.JLabel lbUlica_Czyt;
    private javax.swing.JLabel lbUlica_Pro;
    private javax.swing.JLabel lbWyszukajCzyt_Czyt;
    private javax.swing.JLabel lbWyszukajEgzemplarz_Ks;
    private javax.swing.JLabel lbWyszukajPracownika_Adm;
    private javax.swing.JPanel pAdministracjaPV;
    private javax.swing.JPanel pCzytelnicyPV;
    private javax.swing.JPanel pKsiegozbiorPV;
    private javax.swing.JPanel pProfilPV;
    private javax.swing.JPanel pRezerwacjePV;
    private javax.swing.JPanel pWypozyczeniaPV;
    private javax.swing.JTable tListaCzytelnikow_Czyt;
    private javax.swing.JTable tListaKsiazek_Ks;
    private javax.swing.JTable tListaPracowników_Adm;
    private javax.swing.JTable tListaRezerwacji_Rez;
    private javax.swing.JTable tListaWypozyczonych_Wyp;
    private javax.swing.JTextField tfAutor_Ks;
    private javax.swing.JTextField tfEAN_Ks;
    private javax.swing.JTextField tfEMail_Pro;
    private javax.swing.JTextField tfHaslo_Pro;
    private javax.swing.JTextField tfISBN_Ks;
    private javax.swing.JTextField tfImie_Adm;
    private javax.swing.JTextField tfImie_Czyt;
    private javax.swing.JTextField tfImie_Pro;
    private javax.swing.JTextField tfKodPocztowy_Adm;
    private javax.swing.JTextField tfKodPocztowy_Czyt;
    private javax.swing.JTextField tfKodPocztowy_Pro;
    private javax.swing.JTextField tfLogin_Adm;
    private javax.swing.JTextField tfLogin_Czyt;
    private javax.swing.JTextField tfLogin_Pro;
    private javax.swing.JTextField tfMiejscowosc_Adm;
    private javax.swing.JTextField tfMiejscowosc_Czyt;
    private javax.swing.JTextField tfMiejscowosc_Pro;
    private javax.swing.JTextField tfNazwisko_Adm;
    private javax.swing.JTextField tfNazwisko_Czyt;
    private javax.swing.JTextField tfNazwisko_Pro;
    private javax.swing.JTextField tfNrDomu_Adm;
    private javax.swing.JTextField tfNrDomu_Czyt;
    private javax.swing.JTextField tfNrDomu_Pro;
    private javax.swing.JTextField tfTag_Ks;
    private javax.swing.JTextField tfTytul_Ks;
    private javax.swing.JTextField tfUlica_Adm;
    private javax.swing.JTextField tfUlica_Czyt;
    private javax.swing.JTextField tfUlica_Pro;
    private javax.swing.JTabbedPane tpMain;
    // End of variables declaration//GEN-END:variables
}
