/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteka00;

/**
 *
 * @author Mharcin
 */
public class SzczegEgzemplarza extends javax.swing.JFrame {

    /**
     * Creates new form Szczegoly
     */
    public SzczegEgzemplarza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEAN_SzEgz = new javax.swing.JLabel();
        lbTytul_SzEgz = new javax.swing.JLabel();
        lbTyp_SzEgz = new javax.swing.JLabel();
        lbGatunek_SzEgz = new javax.swing.JLabel();
        lbTagi_SzEgz = new javax.swing.JLabel();
        lbRokWydania_SzEgz = new javax.swing.JLabel();
        lbJezyk_SzEgz = new javax.swing.JLabel();
        lbNrWydania_SzEgz = new javax.swing.JLabel();
        lbLiczbaStron_SzEgz = new javax.swing.JLabel();
        lbStatus_SzEgz = new javax.swing.JLabel();
        lbWydawnictwo_SzEgz = new javax.swing.JLabel();
        lbISBN_SzEgz = new javax.swing.JLabel();
        lbFormat_SzEgz = new javax.swing.JLabel();
        tfEAN_SzEgz = new javax.swing.JTextField();
        tfNrWydania_SzEgz = new javax.swing.JTextField();
        tfRokWydania_SzEgz = new javax.swing.JTextField();
        tfGatunek_SzEgz = new javax.swing.JTextField();
        tfTytul_SzEgz = new javax.swing.JTextField();
        tfLiczbaStron_SzEgz = new javax.swing.JTextField();
        tfISBN_SzEgz = new javax.swing.JTextField();
        tfWydawnictwo_SzEgz = new javax.swing.JTextField();
        tfFormat_SzEgz = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cbJezyk_SzEgz = new javax.swing.JComboBox<>();
        cbStatus_SzEgz = new javax.swing.JComboBox<>();
        cbTyp_SzEgz = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAutorzy_SzEgz = new javax.swing.JTable();
        btZapisz_SzEgz = new javax.swing.JButton();
        lbAutorzy_SzEgz = new javax.swing.JLabel();
        btWycofajZmiany = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lbEAN_SzEgz.setText("EAN");
        lbEAN_SzEgz.setPreferredSize(new java.awt.Dimension(80, 15));

        lbTytul_SzEgz.setText("Tytuł");
        lbTytul_SzEgz.setPreferredSize(new java.awt.Dimension(80, 15));

        lbTyp_SzEgz.setText("Typ");
        lbTyp_SzEgz.setPreferredSize(new java.awt.Dimension(80, 15));

        lbGatunek_SzEgz.setText("Gatunek");
        lbGatunek_SzEgz.setPreferredSize(new java.awt.Dimension(80, 15));

        lbTagi_SzEgz.setText("Tagi");
        lbTagi_SzEgz.setPreferredSize(new java.awt.Dimension(80, 15));

        lbRokWydania_SzEgz.setText("Rok wydania");
        lbRokWydania_SzEgz.setPreferredSize(new java.awt.Dimension(80, 15));

        lbJezyk_SzEgz.setText("Język");
        lbJezyk_SzEgz.setPreferredSize(new java.awt.Dimension(80, 15));

        lbNrWydania_SzEgz.setText("Nr wydania");
        lbNrWydania_SzEgz.setPreferredSize(new java.awt.Dimension(80, 15));

        lbLiczbaStron_SzEgz.setText("Liczba stron");
        lbLiczbaStron_SzEgz.setPreferredSize(new java.awt.Dimension(80, 15));

        lbStatus_SzEgz.setText("Status");
        lbStatus_SzEgz.setPreferredSize(new java.awt.Dimension(80, 15));

        lbWydawnictwo_SzEgz.setText("Wydawnictwo");
        lbWydawnictwo_SzEgz.setPreferredSize(new java.awt.Dimension(80, 15));

        lbISBN_SzEgz.setText("ISBN");
        lbISBN_SzEgz.setPreferredSize(new java.awt.Dimension(80, 15));

        lbFormat_SzEgz.setText("Format");
        lbFormat_SzEgz.setPreferredSize(new java.awt.Dimension(80, 15));

        tfEAN_SzEgz.setPreferredSize(new java.awt.Dimension(200, 19));

        tfNrWydania_SzEgz.setPreferredSize(new java.awt.Dimension(200, 19));

        tfRokWydania_SzEgz.setPreferredSize(new java.awt.Dimension(200, 19));

        tfGatunek_SzEgz.setPreferredSize(new java.awt.Dimension(200, 19));

        tfTytul_SzEgz.setPreferredSize(new java.awt.Dimension(200, 19));

        tfLiczbaStron_SzEgz.setPreferredSize(new java.awt.Dimension(200, 19));

        tfISBN_SzEgz.setPreferredSize(new java.awt.Dimension(200, 19));

        tfWydawnictwo_SzEgz.setPreferredSize(new java.awt.Dimension(200, 19));

        tfFormat_SzEgz.setPreferredSize(new java.awt.Dimension(200, 19));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(200, 75));
        jScrollPane1.setViewportView(jTextArea1);

        cbJezyk_SzEgz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "polski", "arabski", "angielski", "niemiecki" }));
        cbJezyk_SzEgz.setPreferredSize(new java.awt.Dimension(200, 24));

        cbStatus_SzEgz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dostępny", "wypożyczony", "zarezerwowany", "niedostępny", "wycofany", "zagubiony", "przetrzymany", "uszkodzony" }));
        cbStatus_SzEgz.setPreferredSize(new java.awt.Dimension(200, 24));

        cbTyp_SzEgz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kisążka", "czasopismo", "film" }));
        cbTyp_SzEgz.setPreferredSize(new java.awt.Dimension(200, 24));

        tAutorzy_SzEgz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Imię", "Nazwisko", "Data urodzenia", "Data śmierci"
            }
        ));
        jScrollPane2.setViewportView(tAutorzy_SzEgz);

        btZapisz_SzEgz.setText("Zapisz");

        lbAutorzy_SzEgz.setText("Autorzy");

        btWycofajZmiany.setText("Wycofaj zmiany");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbISBN_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfISBN_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbGatunek_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfGatunek_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTyp_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTyp_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTytul_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTytul_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEAN_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEAN_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbJezyk_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJezyk_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbRokWydania_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfRokWydania_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNrWydania_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNrWydania_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbLiczbaStron_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLiczbaStron_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbFormat_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFormat_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbStatus_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbWydawnictwo_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfWydawnictwo_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbStatus_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTagi_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btZapisz_SzEgz))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btWycofajZmiany)
                            .addComponent(jScrollPane1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAutorzy_SzEgz))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEAN_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEAN_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAutorzy_SzEgz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTytul_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTytul_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTyp_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTyp_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGatunek_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGatunek_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbJezyk_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbJezyk_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbRokWydania_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRokWydania_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNrWydania_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNrWydania_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLiczbaStron_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLiczbaStron_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStatus_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStatus_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbWydawnictwo_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWydawnictwo_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFormat_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFormat_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbISBN_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfISBN_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTagi_SzEgz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btZapisz_SzEgz)
                    .addComponent(btWycofajZmiany))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SzczegEgzemplarza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SzczegEgzemplarza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SzczegEgzemplarza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SzczegEgzemplarza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SzczegEgzemplarza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btWycofajZmiany;
    private javax.swing.JButton btZapisz_SzEgz;
    private javax.swing.JComboBox<String> cbJezyk_SzEgz;
    private javax.swing.JComboBox<String> cbStatus_SzEgz;
    private javax.swing.JComboBox<String> cbTyp_SzEgz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbAutorzy_SzEgz;
    private javax.swing.JLabel lbEAN_SzEgz;
    private javax.swing.JLabel lbFormat_SzEgz;
    private javax.swing.JLabel lbGatunek_SzEgz;
    private javax.swing.JLabel lbISBN_SzEgz;
    private javax.swing.JLabel lbJezyk_SzEgz;
    private javax.swing.JLabel lbLiczbaStron_SzEgz;
    private javax.swing.JLabel lbNrWydania_SzEgz;
    private javax.swing.JLabel lbRokWydania_SzEgz;
    private javax.swing.JLabel lbStatus_SzEgz;
    private javax.swing.JLabel lbTagi_SzEgz;
    private javax.swing.JLabel lbTyp_SzEgz;
    private javax.swing.JLabel lbTytul_SzEgz;
    private javax.swing.JLabel lbWydawnictwo_SzEgz;
    private javax.swing.JTable tAutorzy_SzEgz;
    private javax.swing.JTextField tfEAN_SzEgz;
    private javax.swing.JTextField tfFormat_SzEgz;
    private javax.swing.JTextField tfGatunek_SzEgz;
    private javax.swing.JTextField tfISBN_SzEgz;
    private javax.swing.JTextField tfLiczbaStron_SzEgz;
    private javax.swing.JTextField tfNrWydania_SzEgz;
    private javax.swing.JTextField tfRokWydania_SzEgz;
    private javax.swing.JTextField tfTytul_SzEgz;
    private javax.swing.JTextField tfWydawnictwo_SzEgz;
    // End of variables declaration//GEN-END:variables
}
