/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteka00;

/**
 *
 * @author Mharcin
 */
public class SzczegCzytelnika extends javax.swing.JFrame {

    /**
     * Creates new form SzczegEgzemplarza
     */
    public SzczegCzytelnika() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbZapisz_SzCzyt = new javax.swing.JButton();
        lbWstecz_SzCzyt = new javax.swing.JButton();
        lbUsun_SzCzyt = new javax.swing.JButton();
        tfLogin_SzCzyt = new javax.swing.JTextField();
        lbLogin_SzCzyt = new javax.swing.JLabel();
        lbNrDomu_SzCzyt = new javax.swing.JLabel();
        tfNrDomu_SzCzyt = new javax.swing.JTextField();
        tfUlica_SzCzyt = new javax.swing.JTextField();
        lbUlica_SzCzyt = new javax.swing.JLabel();
        tfKodPocztowy_SzCzyt = new javax.swing.JTextField();
        lbKodPocztowy_SzCzyt = new javax.swing.JLabel();
        tfMiejscowosc_SzCzyt = new javax.swing.JTextField();
        lbMIejscowosc_SzCzyt = new javax.swing.JLabel();
        tfNazwisko_SzCzyt = new javax.swing.JTextField();
        lbNazwisko_SzCzyt = new javax.swing.JLabel();
        lbImie_SzCzyt = new javax.swing.JLabel();
        tfImie_SzCzyt = new javax.swing.JTextField();
        lbPrzetrzymanie_SzCzyt = new javax.swing.JLabel();
        tfLiczbaWyp_SzCzyt = new javax.swing.JTextField();
        lbLiczbaWyp_SzCzyt = new javax.swing.JLabel();
        tfDataRejestr_SzCzyt = new javax.swing.JTextField();
        lbDataRejestr_SzCzyt = new javax.swing.JLabel();
        lbEMail_SzCzyt = new javax.swing.JLabel();
        tfEMail_SzCzyt = new javax.swing.JTextField();
        tfZablokowany_SzCzyt = new javax.swing.JTextField();
        lbZablokowany_SzCzyt = new javax.swing.JLabel();
        tfPrzetrzymanie_SzCzyt = new javax.swing.JTextField();
        lbListaWypozyczonych_SzCzyt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tWypozyczone_SzCzyt = new javax.swing.JTable();
        lbZablokuj_SzCzyt = new javax.swing.JButton();
        lbWycofajZmiany_SzCzyt = new javax.swing.JButton();
        lbSzczegolyRez_SzCzyt = new javax.swing.JButton();
        lbListaZarezerwowanych = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tZarezerwowane_SzCzyt = new javax.swing.JTable();
        lbAnulujRezerwacje_SzCzyt = new javax.swing.JButton();
        lbSzczegolyWyp_SzCzyt = new javax.swing.JButton();
        lbPotwierdzZwrot_SzCzyt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lbZapisz_SzCzyt.setText("Zapisz");

        lbWstecz_SzCzyt.setText("Wstecz");

        lbUsun_SzCzyt.setText("Usuń");

        tfLogin_SzCzyt.setText("...");
        tfLogin_SzCzyt.setPreferredSize(new java.awt.Dimension(160, 19));

        lbLogin_SzCzyt.setText("Login");
        lbLogin_SzCzyt.setPreferredSize(new java.awt.Dimension(70, 15));

        lbNrDomu_SzCzyt.setText("Nr domu");
        lbNrDomu_SzCzyt.setPreferredSize(new java.awt.Dimension(70, 15));

        tfNrDomu_SzCzyt.setText("...");
        tfNrDomu_SzCzyt.setPreferredSize(new java.awt.Dimension(160, 19));

        tfUlica_SzCzyt.setText("...");
        tfUlica_SzCzyt.setPreferredSize(new java.awt.Dimension(160, 19));

        lbUlica_SzCzyt.setText("Ulica");
        lbUlica_SzCzyt.setPreferredSize(new java.awt.Dimension(70, 15));

        tfKodPocztowy_SzCzyt.setText("...");
        tfKodPocztowy_SzCzyt.setPreferredSize(new java.awt.Dimension(160, 19));

        lbKodPocztowy_SzCzyt.setText("Kod pocztowy");
        lbKodPocztowy_SzCzyt.setPreferredSize(new java.awt.Dimension(70, 15));

        tfMiejscowosc_SzCzyt.setText("...");
        tfMiejscowosc_SzCzyt.setPreferredSize(new java.awt.Dimension(160, 19));

        lbMIejscowosc_SzCzyt.setText("MIejscowość");
        lbMIejscowosc_SzCzyt.setPreferredSize(new java.awt.Dimension(70, 15));

        tfNazwisko_SzCzyt.setText("...");
        tfNazwisko_SzCzyt.setPreferredSize(new java.awt.Dimension(160, 19));

        lbNazwisko_SzCzyt.setText("Nazwisko");
        lbNazwisko_SzCzyt.setPreferredSize(new java.awt.Dimension(70, 15));

        lbImie_SzCzyt.setText("Imię");
        lbImie_SzCzyt.setPreferredSize(new java.awt.Dimension(70, 15));

        tfImie_SzCzyt.setText("...");
        tfImie_SzCzyt.setPreferredSize(new java.awt.Dimension(160, 19));

        lbPrzetrzymanie_SzCzyt.setText("Przetrzymanie");
        lbPrzetrzymanie_SzCzyt.setPreferredSize(new java.awt.Dimension(70, 15));

        tfLiczbaWyp_SzCzyt.setText("...");
        tfLiczbaWyp_SzCzyt.setPreferredSize(new java.awt.Dimension(160, 19));

        lbLiczbaWyp_SzCzyt.setText("Liczba wypożyczeń");
        lbLiczbaWyp_SzCzyt.setPreferredSize(new java.awt.Dimension(70, 15));

        tfDataRejestr_SzCzyt.setText("...");
        tfDataRejestr_SzCzyt.setPreferredSize(new java.awt.Dimension(160, 19));

        lbDataRejestr_SzCzyt.setText("Data rejestracji");
        lbDataRejestr_SzCzyt.setPreferredSize(new java.awt.Dimension(70, 15));

        lbEMail_SzCzyt.setText("E-mail");
        lbEMail_SzCzyt.setPreferredSize(new java.awt.Dimension(70, 15));

        tfEMail_SzCzyt.setText("...");
        tfEMail_SzCzyt.setPreferredSize(new java.awt.Dimension(160, 19));

        tfZablokowany_SzCzyt.setText("...");
        tfZablokowany_SzCzyt.setPreferredSize(new java.awt.Dimension(160, 19));

        lbZablokowany_SzCzyt.setText("Zablokowany");
        lbZablokowany_SzCzyt.setPreferredSize(new java.awt.Dimension(70, 15));

        tfPrzetrzymanie_SzCzyt.setText("...");
        tfPrzetrzymanie_SzCzyt.setPreferredSize(new java.awt.Dimension(160, 19));

        lbListaWypozyczonych_SzCzyt.setText("Lista wypożyczonych");

        tWypozyczone_SzCzyt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1111", "Mały Książę", "Antoine’a de Saint-Exupéry", "książka", "baśń", "123-456-789"},
                {"1111", "Faust", "J.W. Goethe", "ksiażka", "dramat", "777-777-777"}
            },
            new String [] {
                "EAN", "Tytuł", "Autor", "Typ", "Tagi", "ISBN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tWypozyczone_SzCzyt);

        lbZablokuj_SzCzyt.setText("Zablokuj");

        lbWycofajZmiany_SzCzyt.setText("Wycofaj zmiany");

        lbSzczegolyRez_SzCzyt.setText("Szczegóły");
        lbSzczegolyRez_SzCzyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSzczegolyRez_SzCzytActionPerformed(evt);
            }
        });

        lbListaZarezerwowanych.setText("Lista zarezerwowanych");

        tZarezerwowane_SzCzyt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1111", "Mały Książę", "Antoine’a de Saint-Exupéry", "książka", "baśń", "123-456-789"},
                {"1111", "Faust", "J.W. Goethe", "ksiażka", "dramat", "777-777-777"}
            },
            new String [] {
                "EAN", "Tytuł", "Autor", "Typ", "Tagi", "ISBN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tZarezerwowane_SzCzyt);

        lbAnulujRezerwacje_SzCzyt.setText("Anuluj rezerwację");
        lbAnulujRezerwacje_SzCzyt.setPreferredSize(new java.awt.Dimension(70, 25));

        lbSzczegolyWyp_SzCzyt.setText("Szczegóły");
        lbSzczegolyWyp_SzCzyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSzczegolyWyp_SzCzytActionPerformed(evt);
            }
        });

        lbPotwierdzZwrot_SzCzyt.setText("Potwierdź zwrot");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbImie_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfImie_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNazwisko_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNazwisko_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbMIejscowosc_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMiejscowosc_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbUlica_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUlica_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNrDomu_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNrDomu_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbKodPocztowy_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfKodPocztowy_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbLogin_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLogin_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDataRejestr_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataRejestr_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbLiczbaWyp_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLiczbaWyp_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEMail_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEMail_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbZablokowany_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfZablokowany_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPrzetrzymanie_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPrzetrzymanie_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbWstecz_SzCzyt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbWycofajZmiany_SzCzyt))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbZapisz_SzCzyt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbUsun_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbZablokuj_SzCzyt)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbSzczegolyRez_SzCzyt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAnulujRezerwacje_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbListaWypozyczonych_SzCzyt)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbListaZarezerwowanych)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbSzczegolyWyp_SzCzyt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPotwierdzZwrot_SzCzyt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbImie_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfImie_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbListaWypozyczonych_SzCzyt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNazwisko_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNazwisko_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMIejscowosc_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMiejscowosc_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbKodPocztowy_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfKodPocztowy_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbUlica_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUlica_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNrDomu_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNrDomu_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLogin_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLogin_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEMail_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEMail_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDataRejestr_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDataRejestr_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLiczbaWyp_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLiczbaWyp_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPrzetrzymanie_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPrzetrzymanie_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbZablokowany_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfZablokowany_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSzczegolyWyp_SzCzyt)
                            .addComponent(lbPotwierdzZwrot_SzCzyt))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbListaZarezerwowanych)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbSzczegolyRez_SzCzyt)
                        .addComponent(lbAnulujRezerwacje_SzCzyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbUsun_SzCzyt)
                        .addComponent(lbZablokuj_SzCzyt)
                        .addComponent(lbZapisz_SzCzyt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbWstecz_SzCzyt)
                    .addComponent(lbWycofajZmiany_SzCzyt))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbSzczegolyWyp_SzCzytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSzczegolyWyp_SzCzytActionPerformed
        // TODO add your handling code here:
        SzczegEgzemplarza szczegoly = new SzczegEgzemplarza();
        szczegoly.setVisible(true);
    }//GEN-LAST:event_lbSzczegolyWyp_SzCzytActionPerformed

    private void lbSzczegolyRez_SzCzytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSzczegolyRez_SzCzytActionPerformed
        // TODO add your handling code here:
        SzczegEgzemplarza szczegoly = new SzczegEgzemplarza();
        szczegoly.setVisible(true);
    }//GEN-LAST:event_lbSzczegolyRez_SzCzytActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SzczegEgzemplarza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SzczegEgzemplarza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SzczegEgzemplarza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SzczegEgzemplarza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SzczegEgzemplarza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lbAnulujRezerwacje_SzCzyt;
    private javax.swing.JLabel lbDataRejestr_SzCzyt;
    private javax.swing.JLabel lbEMail_SzCzyt;
    private javax.swing.JLabel lbImie_SzCzyt;
    private javax.swing.JLabel lbKodPocztowy_SzCzyt;
    private javax.swing.JLabel lbLiczbaWyp_SzCzyt;
    private javax.swing.JLabel lbListaWypozyczonych_SzCzyt;
    private javax.swing.JLabel lbListaZarezerwowanych;
    private javax.swing.JLabel lbLogin_SzCzyt;
    private javax.swing.JLabel lbMIejscowosc_SzCzyt;
    private javax.swing.JLabel lbNazwisko_SzCzyt;
    private javax.swing.JLabel lbNrDomu_SzCzyt;
    private javax.swing.JButton lbPotwierdzZwrot_SzCzyt;
    private javax.swing.JLabel lbPrzetrzymanie_SzCzyt;
    private javax.swing.JButton lbSzczegolyRez_SzCzyt;
    private javax.swing.JButton lbSzczegolyWyp_SzCzyt;
    private javax.swing.JLabel lbUlica_SzCzyt;
    private javax.swing.JButton lbUsun_SzCzyt;
    private javax.swing.JButton lbWstecz_SzCzyt;
    private javax.swing.JButton lbWycofajZmiany_SzCzyt;
    private javax.swing.JLabel lbZablokowany_SzCzyt;
    private javax.swing.JButton lbZablokuj_SzCzyt;
    private javax.swing.JButton lbZapisz_SzCzyt;
    private javax.swing.JTable tWypozyczone_SzCzyt;
    private javax.swing.JTable tZarezerwowane_SzCzyt;
    private javax.swing.JTextField tfDataRejestr_SzCzyt;
    private javax.swing.JTextField tfEMail_SzCzyt;
    private javax.swing.JTextField tfImie_SzCzyt;
    private javax.swing.JTextField tfKodPocztowy_SzCzyt;
    private javax.swing.JTextField tfLiczbaWyp_SzCzyt;
    private javax.swing.JTextField tfLogin_SzCzyt;
    private javax.swing.JTextField tfMiejscowosc_SzCzyt;
    private javax.swing.JTextField tfNazwisko_SzCzyt;
    private javax.swing.JTextField tfNrDomu_SzCzyt;
    private javax.swing.JTextField tfPrzetrzymanie_SzCzyt;
    private javax.swing.JTextField tfUlica_SzCzyt;
    private javax.swing.JTextField tfZablokowany_SzCzyt;
    // End of variables declaration//GEN-END:variables
}
